# Generated by Django 3.1 on 2022-08-14 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OTT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='ott',
            name='distribution',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='genre',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='image_route',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='information',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='movie_route',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='nation',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='ralease_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ott',
            name='running_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ott',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTT.character')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OTT.ott')),
            ],
        ),
    ]
